export const DB_NAME = "collabboard";

export const APP_NAME = "CollabBoard";

export const ACTIVITY_TYPES = {
  CREATE_TASK: "CREATE_TASK",
  UPDATE_TASK: "UPDATE_TASK",
  DELETE_TASK: "DELETE_TASK",
  MOVE_TASK: "MOVE_TASK",
  UPDATE_TASK_STATUS: "UPDATE_TASK_STATUS",
  CREATE_BOARD: "CREATE_BOARD",
  DELETE_BOARD: "DELETE_BOARD",
  UPDATE_BOARD: "UPDATE_BOARD",
  SEND_MESSAGE: "SEND_MESSAGE",
  DELETE_MESSAGE: "DELETE_MESSAGE",
  ADD_COMMENT: "ADD_COMMENT",
  DELETE_COMMENT: "DELETE_COMMENT",
  ADD_MEMBER: "ADD_MEMBER",
  REMOVE_MEMBER: "REMOVE_MEMBER",
};

export const ACTIVITY_TYPES_VALUES = Object.values(ACTIVITY_TYPES);

export const RATE_LIMITS = {
  COMMENTS_PER_MINUTE: 5,
  MESSAGES_PER_10_SECONDS: 10,
};
